// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
list linfit(doubles xs, doubles ys);
extern "C" SEXP _gmatlib_linfit(SEXP xs, SEXP ys) {
  BEGIN_CPP11
    return cpp11::as_sexp(linfit(cpp11::as_cpp<cpp11::decay_t<doubles>>(xs), cpp11::as_cpp<cpp11::decay_t<doubles>>(ys)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_gmatlib_linfit", (DL_FUNC) &_gmatlib_linfit, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_gmatlib(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
