# Generated by cpp11: do not edit by hand

linfit_ <- function(xs, ys) {
  .Call(`_gmatlib_linfit_`, xs, ys)
}

div_dif_ <- function(xs, ys) {
  .Call(`_gmatlib_div_dif_`, xs, ys)
}

newton_basis_ <- function(x, xs) {
  .Call(`_gmatlib_newton_basis_`, x, xs)
}

alter_johnson_ <- function(ys, t) {
  .Call(`_gmatlib_alter_johnson_`, ys, t)
}

find_periods_ <- function(xs, ys, tol) {
  .Call(`_gmatlib_find_periods_`, xs, ys, tol)
}
